version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser
    volumes:
      - mysql-data:/var/lib/mysql
    user: "1000:1000"  # Run as non-root user to avoid ASL logging issue

volumes:
  mysql-data:
