version: '3.8'

services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     # KEYCLOAK_USER: kcuser
  #     # KEYCLOAK_PASSWORD: kcpassword
  #   ports:
  #     - "8080:8080"
  #   entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

  budget-todo-keycloak:
    image: budget-todo-keycloak:latest
    ports:
      - '8080:8080'
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: rootpassword
      DB_DATABASE: keycloak_db
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import:rw

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budget_todo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  budget_todo_be:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      budget-todo-keycloak:
        condition: service_started

volumes:
  mysql-data: